name: ResearchChain
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-types=0.6.0
  - anyio=4.2.0
  - black=24.4.2
  - ca-certificates=2024.3.11
  - click=8.1.7
  - exceptiongroup=1.2.0
  - fastapi=0.103.0
  - idna=3.7
  - krb5=1.20.1
  - ld_impl_linux-64=2.36.1
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpq=12.17
  - libstdcxx-ng=11.2.0
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - openssl=3.0.14
  - packaging=23.2
  - pathspec=0.10.3
  - pip=24.0
  - platformdirs=3.10.0
  - psycopg2=2.9.9
  - python=3.9.7
  - python_abi=3.9
  - readline=8.2
  - setuptools=69.5.1
  - sniffio=1.3.0
  - sqlite=3.45.3
  - starlette=0.27.0
  - tk=8.6.14
  - tomli=2.0.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - dataclasses-json==0.6.4
      - diskcache==5.6.3
      - eval-type-backport==0.2.0
      - faiss-cpu==1.7.2
      - filelock==3.13.4
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - google==3.0.0
      - greenlet==3.0.3
      - h11==0.14.0
      - huggingface-hub==0.22.2
      - jinja2==3.1.3
      - jsonpatch==1.33
      - jsonpointer==2.4
      - langchain==0.1.16
      - langchain-community==0.0.33
      - langchain-core==0.1.43
      - langchain-text-splitters==0.0.1
      - langsmith==0.1.48
      - llama-cpp-python==0.2.61
      - markupsafe==2.1.5
      - marshmallow==3.21.1
      - multidict==6.0.5
      - numpy==1.26.4
      - orjson==3.10.1
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pyyaml==6.0.1
      - regex==2024.4.16
      - requests==2.31.0
      - soupsieve==2.5
      - sqlalchemy==2.0.29
      - tenacity==8.2.3
      - tiktoken==0.6.0
      - tinydb==4.8.0
      - tqdm==4.66.2
      - typing-inspect==0.9.0
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - yarl==1.9.4
