import { SummaryTask } from "../types/TaskType";

export const data: { task: SummaryTask[] } = {
  task: [
    {
      uuid: "11",
      prompt: "Summary task with a concise prompt",
      mode: "Docs",
      timestamp: 1717501716.700594,
      executing: false,
      execution_date: 0,
      completed: false,
      completion_date: 0,
      completion_result: "Summary result for task 11Summary result for task 11Summary result for task 11Summary result for task 11Summary result for task 11Summary result for task 11Summary result for task 11",
    },
    {
      uuid: "12",
      prompt: "Another summary task to test integration",
      mode: "Wiki",
      timestamp: 1717485516.700594,
      executing: false,
      execution_date: 0,
      completed: true,
      completion_date: 0,
      completion_result: "Result for task 12",
    },
    {
      uuid: "13",
      prompt: "Testing summary task for news mode",
      mode: "News",
      timestamp: 1717330716.700594,
      executing: false,
      execution_date: 0,
      completed: true,
      completion_date: 0,
      completion_result: "Detailed result for news task",
    },
    {
      uuid: "14",
      prompt: "Short summary task",
      mode: "Docs",
      timestamp: 1717502916.700594,
      executing: false,
      execution_date: 0,
      completed: false,
      completion_date: 0,
      completion_result: "Short result",
    },
    {
      uuid: "15",
      prompt: "Detailed summary task with extensive data",
      mode: "Wiki",
      timestamp: 1717499916.700594,
      executing: true,
      execution_date: 0,
      completed: false,
      completion_date: 0,
      completion_result: "Detailed result for task 15 with extensive data",
    },
    {
      uuid: "16",
      prompt: "News summary task for verification",
      mode: "News",
      timestamp: 1717244316.700594,
      executing: false,
      execution_date: 0,
      completed: true,
      completion_date: 0,
      completion_result: "Final result for news task",
    },
    {
      uuid: "17",
      prompt: "Verification task for docs mode",
      mode: "Docs",
      timestamp: 1717157916.700594,
      executing: false,
      execution_date: 0,
      completed: true,
      completion_date: 0,
      completion_result: "Verification complete for docs task",
    },
    {
      uuid: "18",
      prompt: "Wiki mode summary task for testing data mock",
      mode: "Wiki",
      timestamp: 1717071516.700594,
      executing: false,
      execution_date: 0,
      completed: false,
      completion_date: 0,
      completion_result: "Mock data testing for wiki task",
    },
    {
      uuid: "19",
      prompt: "Final news mode task to verify integration",
      mode: "News",
      timestamp: 1716985116.700594,
      executing: false,
      execution_date: 0,
      completed: true,
      completion_date: 0,
      completion_result: "Final integration result for news task",
    },
    {
      uuid: "20",
      prompt: "Last summary task for docs mode",
      mode: "Docs",
      timestamp: 1716898716.700594,
      executing: true,
      execution_date: 0,
      completed: false,
      completion_date: 0,
      completion_result: "Last summary task in progress for docs",
    },
  ],
};
