apiVersion: v1
data:
  entrypoint.sh: |-
    #!/bin/bash

    /bin/ollama serve &

    pid=$!

    sleep 5

    ollama pull zephyr:7b-beta-q5_K_M
    ollama pull nomic-embed-text

    wait $pid
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: ollama
  name: ollama-cm1
