import { CrawlHistoryItem } from "./page";

export const data: CrawlHistoryItem = {
  task: [
    {
      uuid: "1",
      prompt: "Huge prompt huge prompt huge prompt huge prompt huge prompt",
      mode: "Docs",
      completed: false,
      completion_result: null,
      executing: false,
      required_crawl_tasks: [],
      completion_date: 0,
      execution_date: 0,
      timestamp: 1717501716.700594,
    },
    {
      uuid: "2",
      prompt: "Another prompt with slightly less length",
      mode: "Wiki",
      completed: true,
      completion_result: null,
      executing: false,
      required_crawl_tasks: [],
      completion_date: 0,
      execution_date: 0,
      timestamp: 1717485516.700594,
    },
    {
      uuid: "3",
      prompt: "Prompt for testing purposes only",
      mode: "News",
      completed: true,
      completion_result: null,
      executing: false,
      required_crawl_tasks: [],
      completion_date: 0,
      execution_date: 0,
      timestamp: 1717330716.700594,
    },
    {
      uuid: "4",
      prompt: "Short prompt",
      mode: "Docs",
      completed: false,
      completion_result: null,
      executing: false,
      required_crawl_tasks: [],
      completion_date: 0,
      execution_date: 0,
      timestamp: 1717502916.700594,
    },
    {
      uuid: "5",
      prompt: "This is a very detailed prompt meant for extensive testing of the system's capabilities and performance under stress",
      mode: "Wiki",
      completed: false,
      completion_result: null,
      executing: true,
      required_crawl_tasks: [],
      completion_date: 0,
      execution_date: 0,
      timestamp: 1717499916.700594,
    },
    {
      uuid: "6",
      prompt: "Test prompt for news mode",
      mode: "News",
      completed: true,
      completion_result: null,
      executing: false,
      required_crawl_tasks: [],
      completion_date: 0,
      execution_date: 0,
      timestamp: 1717244316.700594,
    },
    {
      uuid: "7",
      prompt: "Another doc mode prompt for verification",
      mode: "Docs",
      completed: true,
      completion_result: null,
      executing: false,
      required_crawl_tasks: [],
      completion_date: 0,
      execution_date: 0,
      timestamp: 1717157916.700594,
    },
    {
      uuid: "8",
      prompt: "Wiki mode prompt for testing data mock",
      mode: "Wiki",
      completed: false,
      completion_result: null,
      executing: false,
      required_crawl_tasks: [],
      completion_date: 0,
      execution_date: 0,
      timestamp: 1717071516.700594,
    },
    {
      uuid: "9",
      prompt: "News mode prompt to verify integration",
      mode: "News",
      completed: true,
      completion_result: null,
      executing: false,
      required_crawl_tasks: [],
      completion_date: 0,
      execution_date: 0,
      timestamp: 1716985116.700594,
    },
    {
      uuid: "10",
      prompt: "Final prompt for docs mode",
      mode: "Docs",
      completed: false,
      completion_result: null,
      executing: true,
      required_crawl_tasks: [],
      completion_date: 0,
      execution_date: 0,
      timestamp: 1716898716.700594,
    },
  ],
};
